### ISSUE TITLE
Feature Request: Limit maximum number of free VMs in pool

### ISSUE THREAD

**Issue by MissingRoberto** [cloudfoundry-community/bosh-softlayer-baremetal-server-release#44]
hey @maximilien, 

can you evaluate how to add a limitation of the number of VMs marked as **free**? 

For instance, it that limit is set to 20 VMs and when the 21st VM is released, it will be directly removed from SL.

**Comment by maximilien** [comment]
I think it would be fair to ask for this to be a configuration settings?

/cc @zhanggbj @mattcui @jianqiu
