### ISSUE TITLE
Implementation of VPS client should be located here

### ISSUE THREAD

**Issue by MissingRoberto** [cloudfoundry-community/bosh-softlayer-baremetal-server-release#45]
Hi @maximilien, 

I was trying to create a CLI for working with the VPS server, and I found out that the only client implementation you have is in https://github.com/cloudfoundry/bosh-softlayer-cpi-release/tree/master/src/bosh-softlayer-cpi/softlayer/pool/client. 

Could you think about moving it here? 

It would make it more reusable.

**Comment by zhanggbj** [comment]
Hi @jszroberto ,

The client code can be generated using [go-swagger](https://github.com/go-swagger/go-swagger) and the swagger.json we used for server is located [here](https://github.com/cloudfoundry-community/bosh-softlayer-pool-server-release/blob/master/src/github.com/cloudfoundry-community/vps/generated/docs/swagger.json).

**Comment by maximilien** [comment]
Did that answer your question @jszroberto? Can we close this as resolved?

**Comment by MissingRoberto** [comment]
yes, thank you very much @zhanggbj @maximilien !!!
